openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /something:
    get:
      operationId: getSomething
      responses:
        '200':
          description: A paged array of pets